import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";

// const cairo = Cairo({ subsets: ["latin"] });
// const exo2 = Exo_2({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Task List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=''>
        <Toaster position="top-center" reverseOrder={false} />
        {children}
      </body>
    </html>
  );
}
